name = "SExpressions"
uuid = "eaa8e424-c5f6-11e8-1b3d-d576ba0eee97"
author = ["Fengyang Wang <fengyang.wang.0@gmail.com>"]
version = "1.0.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FunctionalCollections = "de31a74c-ac4f-5751-b3fd-e18cd04993ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Automa = "0.7.0, 0.8"
DataStructures = "0.14.0, 0.17, 0.18"
FunctionalCollections = "0.4.0, 0.5"
Reexport = "0.2.0"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
